### ISSUE TITLE
Anpassen der Übersetzunglängen

### ISSUE THREAD

**Issue by AllanScheSar** [KerbalSpaceProgramDe/KSP-Deutsch-Patch#11]
- Übersetzung wird nicht komplett angezeigt. In KSP wird angezeigt "Translation und Rotation t" ([Quellzeile]

(https://github.com/KerbalSpaceProgramDe/KSP-Deutsch-Patch/blob/master/GameData/KSP%20Deutsch%20Patch/Settings.cfg#L573)
![screenshot8](https://cloud.githubusercontent.com/assets/10440688/16707271/5b4bea14-45c8-11e6-96d8-ac5d287b65c9.png)

**Comment by Idinyphe** [comment]
Ist natürlich mein Fehler und mir bei Durchsicht auch nicht aufgefallen, tut mir leid, wer fixed es?

**Comment by AllanScheSar** [comment]
Dafür kannst du nichts. Wie wir das fixen steht auch noch nicht fest.
Das einfachst wird wohl sein es abzukürzen mit "Transl. u. Rot wechsel" oder ähnliches.
Du kannst es gern fixen. Wenn ich dann am Wochenende wieder drüber gehe, nehme ich mir alle offenen Issues vor.

**Comment by AllanScheSar** [comment]
Ersetzt mit "Wechsel Transl. und Rot."
