### ISSUE TITLE
Punkte fehlen

### ISSUE THREAD

**Issue by AllanScheSar** [KerbalSpaceProgramDe/KSP-Deutsch-Patch#13]
Folgende Controlls wurden nicht übersetzt:
Übersetzungen für folgende Punkte fehlen:
- Emergency Abort
- Custom Action 1-10
- Throttle Cut-off
- LeftShift
- LeftControl
- LeftAlt
- Toggle Local/Absolute
- Cycle Symmetry Mode

**Comment by StollD** [comment]
Die Tastennamen würde ich allgemein nicht übersetzen. LinksAlt klingt komisch und ich hab keine Idee wie man das Platzsparend lösen kann.

**Comment by AllanScheSar** [comment]
Wie wäre es denn mit Alt links ;)
Das ist genauso Platzsparend und das nicht zu übersetzen steht dem Ziel entgegen. Dann lieber an der Stelle die Schriftart kleiner machen.

**Comment by AllanScheSar** [comment]
Bugs behoben und getestet. 
Issue wird geschlossen.
