### ISSUE TITLE
Loading... wird nicht übersetzt

### ISSUE THREAD

**Issue by AllanScheSar** [KerbalSpaceProgramDe/KSP-Deutsch-Patch#14]
Die Grafik (unten rechts) beim Wechseln der Szene  wird nicht übersetzt.
Wenn man also vom VAB zurück zur KSC geht. Die Loading Grafik meine ich.

**Comment by AllanScheSar** [comment]
@ThomasKerman handelt es sich dabei ebenfalls um eine Grafik, die noch nicht eingebaut ist?
So wie im Issue 18 bereits angesprochen?
https://github.com/KerbalSpaceProgramDe/KSP-Deutsch-Patch/issues/18

**Comment by StollD** [comment]
Nein, ist keine Grafik, scheint einfach nur ein Fehler in den Configs zu sein. Da muss irgendwo

```
text = Loading\.\.\.
```

rein.

**Comment by StollD** [comment]
Nachtrag: Joa, wenn ich die Übersetzung fixe kommt sowas bei raus: http://i.imgur.com/in9Vhla.png

Ich plädiere für "einfach weglassen, kümmert eh keinen"

**Comment by AllanScheSar** [comment]
Okay, aber lassen das Thema erst einmal offen.

**Comment by AllanScheSar** [comment]
@ThomasKerman gibt es einen neuen Stand zu diesem Thema? 
Können wir das Loadingsfeld übersetzen oder nicht?

**Comment by StollD** [comment]
Nein, buggt rum

Wie ich aber schon wo anders gesagt hab: Ist jetzt nicht kritisch

**Comment by AllanScheSar** [comment]
Nicht kritisch ist relativ, denn es würde ja zu einer 100 % Übersetzung gehören, wie jeder anderer Text.
Aber da kann man nichts machen und wir machen eben das beste in der Zeit, bis SQUAD etwas präsentiert.

Daher wird das Thema nun geschlossen - danke fürs erneute prüfen.

**Comment by StollD** [comment]
Wir schaffen die 100% im Moment eh noch nicht, also was solls
