### ISSUE TITLE
Globale Uhr wird nicht übersetzt

### ISSUE THREAD

**Issue by AllanScheSar** [KerbalSpaceProgramDe/KSP-Deutsch-Patch#15]
Die globale KSP Uhr wird nicht übersetzt.
Ich weiß allerdings nicht, wo und wie ich das übersetzen soll.

![screenshot16](https://cloud.githubusercontent.com/assets/10440688/16880884/bac564ea-4ab7-11e6-8b6a-8d77e791bf97.png)

@ThomasKerman  wie gehen wir vor?

**Comment by StollD** [comment]
Würde ich erstmal auslassen bis das ganze Ding performanter läuft. Wir müssen ja nicht unnötig Rechenleistung verbrauchen

**Comment by AllanScheSar** [comment]
Es ist also nichts in den Log Dateien?

**Comment by StollD** [comment]
Doch klar, und selbst wenn wäre das jetzt auch nicht das Problem. Es ist nur etwas unsinnig wenn das Plugin eh schon laggt noch eine Übersetzung einzubauen die jeden Tick neu angewendet werden muss (=> Uhr updated)

**Comment by AllanScheSar** [comment]
@ThomasKerman ich nehme an, dass wir diesen Teil der Übersetzung außen vor lassen, um die Performance nicht weiter zu beeinträchtigen?
Wenn ja, dann schließen wir dieses Thema (leider).
