### ISSUE TITLE
Plugin Performance

### ISSUE THREAD

**Issue by StollD** [KerbalSpaceProgramDe/KSP-Deutsch-Patch#19]
Da muss ich mich nochmal ransetzen und was basteln

**Comment by AllanScheSar** [comment]
Kannst du nicht die Übersetzungen alle beim Start von KSP laden? Dann dauert dies zwar länger. Aber solch unschöne 2 Sekunden Wartezeit, bis der deutsche Text erscheint oder Performanceprobleme im Spiel treten dann nicht mehr auf.
Wobei ich keine Performanceprobleme beim Bauen und fliegen hatte.

**Comment by StollD** [comment]
Könnte ich. Wenn die Texte da schon da wären. Ich kann nur editieren was schon existiert. :wink:

**Comment by AllanScheSar** [comment]
Dann fang doch mit dem Hauptmenü und Settings an. Diese Sachen stehen schon und sind gepürft. Bugs sollten dazu auch keine mehr offen sein, da ich diese am Freitag alle geschlossen habe.
Flight stimmt ebenfalls soweit.

Bau diese bitte einmal ein und wir sehen, was sich wie verbessert im Spiel.

P.S.: eine neue Version vom KDP wäre wieder angesagt, nachdem ich so viele P2 Bugs geschlossen habe. Dies könntest du ja mit der statischen Einbindung verbinden und uns heute Abend eine Version zur Verfügung stellen?

**Comment by StollD** [comment]
Ich rede nicht von Übersetzungen sondern von den Komponenten die die Texte ingame darstellen.

**Comment by AllanScheSar** [comment]
Ach so. Wäre es nicht möglich KSP quasi zu Beginn einmal alles klicken zu lassen (ohne das es der User sieht, weil das ScreenUpdate = false ist)? Damit hätten wir dann alle Komponenten in die der Text eingesetzt wird.
Und wenn das nicht geht, dann sollte es wenigstens soweit statisch sein, dass bereits einmal geladene Texte beim nächsten Aufruf nicht wieder geladen werden.
In den Einstellungen ist es so, wenn ich die Seiten wechsel und wieder zur ersten Seite gehe, dann wird wieder die Übersetzung geladen (ca. 2 Sekunden). Aber diese wurde ja bereits übersetzt beim ersten Aufruf.

**Comment by StollD** [comment]
Dafür müsste ich KSP einmal komplett durchladen. Das ist nicht davon abhängig was geklickt wird sondern welche Objekte erstellt werden (was meistens beim Szenenwechsel passiert)

**Comment by AllanScheSar** [comment]
Und ist es möglich KSP komplett durchzuladen?
10 Sekunden mehr Ladezeit zu Beginn sind besser als während des Spiels, weil die Lags den Fluss stören.

**Comment by StollD** [comment]
Nein, ist es nicht. ;)

**Comment by StollD** [comment]
Ich hab jetzt ein bisschen am Framework geschraubt: https://github.com/KerbalSpaceProgramDe/KSP-Deutsch-Patch/commit/a06eaca770196ece6ffa6fc55d6ac6daabd7228a

Es verbessert nicht direkt die Performance, aber es gibt uns einige Möglichkeiten:
- [ ] Wir müssen alle Übersetzungen die nur in einer Szene aktiv sind mit scenes Werten ausstatten, damit das Plugin die in anderen Szenen ignoriert und nicht so viel Zeit mit dem Regex Check verschwendet
- [ ] Wir müssen alle unnötigen und sinnlosen Übersetzungen löschen, damit das Plugin mit denen keine Zeit verschwendet

Ach ja, und das alles natürlich bis gestern.

**Comment by AllanScheSar** [comment]
Thomas hast du eine Vorlage für mich, wie die Szenenzuordnung aussehen muss, dann würde ich die Eintragung durchführen.
Bitte teilen mir auch mit, welche Szenen unterschieden werden.

**Comment by StollD** [comment]
```
scene = <Szene>
```

in den TRANSLATION { } Sektionen.

<Szene> kann für folgendes stehen:
- LOADING
- MAINMENU
- SETTINGS
- CREDITS
- SPACECENTER
- TRACKINGSTATION
- EDITOR
- FLIGHT

**Comment by AllanScheSar** [comment]
Werde ich nachher in der Kaffeepause mit einpflegen. Dabei sollte ich natürlich Sachen wie Abbrechen oder Anwenden keiner Szene zuordnen, da dieses mehrfach vorkommen und dies natürlich in verschiedenen Szenen.
Wenn meine Annahme koorekt ist, dann bitte mit einem Daumen bestätigen.

**Comment by AllanScheSar** [comment]
Ich habe nun für Settings, Credits, MainMenu und Tracking die Scene hinzugefügt.
Aber bei Flight bin ich mir unsicher. Soll ich zum testen einfach mal überall scene reinsetzen und dann schauen wir, was noch übersetzt ist?

**Comment by StollD** [comment]
Sagen wirs mal so: Es ist besser geworden. Wenn wir jetzt noch den ganzen Quatsch rausnehmen kann man da noch was rausholen

**Comment by AllanScheSar** [comment]
Was ist für dich Quatsch?

**Comment by StollD** [comment]
Sachen wie das hier https://github.com/KerbalSpaceProgramDe/KSP-Deutsch-Patch/blob/master/GameData/KSP%20Deutsch%20Patch/LOADING_v01.CFG#L258-L262

**Comment by AllanScheSar** [comment]
Alles klar ich weiß Bescheid und werde darauf achten. Aber viel macht das definitiv nicht aus.

**Comment by StollD** [comment]
Mit 1.2 ist die Performance akzeptable.

Ich mach hier mal zu
