### ISSUE TITLE
Codes in der Editordatei überprüfen

### ISSUE THREAD

**Issue by AllanScheSar** [KerbalSpaceProgramDe/KSP-Deutsch-Patch#21]
Hallo @ThomasKerman ,

bitte schau dir in der Editordatei folgende Zeilen an:
- 414 https://github.com/KerbalSpaceProgramDe/KSP-Deutsch-Patch/blob/master/GameData/KSP%20Deutsch%20Patch/Editor.cfg#L414
- 426 https://github.com/KerbalSpaceProgramDe/KSP-Deutsch-Patch/blob/master/GameData/KSP%20Deutsch%20Patch/Editor.cfg#L426
- 438 https://github.com/KerbalSpaceProgramDe/KSP-Deutsch-Patch/blob/master/GameData/KSP%20Deutsch%20Patch/Editor.cfg#L438
- 450 https://github.com/KerbalSpaceProgramDe/KSP-Deutsch-Patch/blob/master/GameData/KSP%20Deutsch%20Patch/Editor.cfg#L450
- 462 https://github.com/KerbalSpaceProgramDe/KSP-Deutsch-Patch/blob/master/GameData/KSP%20Deutsch%20Patch/Editor.cfg#L462
- 474 https://github.com/KerbalSpaceProgramDe/KSP-Deutsch-Patch/blob/master/GameData/KSP%20Deutsch%20Patch/Editor.cfg#L474
- 486 https://github.com/KerbalSpaceProgramDe/KSP-Deutsch-Patch/blob/master/GameData/KSP%20Deutsch%20Patch/Editor.cfg#L486
- 515 https://github.com/KerbalSpaceProgramDe/KSP-Deutsch-Patch/blob/master/GameData/KSP%20Deutsch%20Patch/Editor.cfg#L515
- 521 https://github.com/KerbalSpaceProgramDe/KSP-Deutsch-Patch/blob/master/GameData/KSP%20Deutsch%20Patch/Editor.cfg#L521
- 545 https://github.com/KerbalSpaceProgramDe/KSP-Deutsch-Patch/blob/master/GameData/KSP%20Deutsch%20Patch/Editor.cfg#L545
- 569 https://github.com/KerbalSpaceProgramDe/KSP-Deutsch-Patch/blob/master/GameData/KSP%20Deutsch%20Patch/Editor.cfg#L569
- 683 https://github.com/KerbalSpaceProgramDe/KSP-Deutsch-Patch/blob/master/GameData/KSP%20Deutsch%20Patch/Editor.cfg#L683
- 1096 https://github.com/KerbalSpaceProgramDe/KSP-Deutsch-Patch/blob/master/GameData/KSP%20Deutsch%20Patch/Editor.cfg#L1096
- 1174 https://github.com/KerbalSpaceProgramDe/KSP-Deutsch-Patch/blob/master/GameData/KSP%20Deutsch%20Patch/Editor.cfg#L1174
- 1281 https://github.com/KerbalSpaceProgramDe/KSP-Deutsch-Patch/blob/master/GameData/KSP%20Deutsch%20Patch/Editor.cfg#L1281

In diesen Zeilen gibt es Codes, welchen ich nicht abschließend Überprüfen konnte.

**Comment by StollD** [comment]
1. Ist ne 1:1 übersetzung, kein Regex
2. siehe 1.
3. Mass und Cost übersetzen, ansonsten gut
4. gut
5. siehe 1.
6. gut
7. gut
8. gut
9. siehe 1., mit der Ausnahme dass da ein Regex reinmuss, bei den Nummern
10. gut
11. siehe 1.
12. gut
13. gut
14. gut
15. echt jetzt? :D Das ist normaler text.

**Comment by AllanScheSar** [comment]
Hallo Thomas,

ich habe die Nummer drei (Zeile 438) angepasst. Nur verstehe ich nicht, was bei Nummer neun (Zeile 521) verändert werden muss.
Schaust du dir das bitte an und veränderst es ggf.

**Comment by AllanScheSar** [comment]
angepasst.
