### ISSUE TITLE
Sporadische Aussetzer beim Übersetzen?

### ISSUE THREAD

**Issue by AllanScheSar** [KerbalSpaceProgramDe/KSP-Deutsch-Patch#23]
Es werden nicht alle Stellen übersetzt.
Dies ist zum Beispiel beim Auswahlmenü für Crafts zu sehen.

Woran liegt dies?

![offnen menu](https://cloud.githubusercontent.com/assets/10440688/19896980/7fb620ac-a056-11e6-86b7-222c25dbe26d.JPG)

**Comment by StollD** [comment]
Warscheinlich hat da einer den Regex vergeigt

**Comment by AllanScheSar** [comment]
Würdest du diesen dir die Woche noch anschauen können?
Ich frage mich eben, warum es mal geht und mal nicht. Wenn der Regex falsch wäre, sollte doch alles nicht klappen.

**Comment by StollD** [comment]
Weil "stage" und "stages" zwei verschiedene Wörter sind. Deshalb erkennt der nur die Hälfte

**Comment by AllanScheSar** [comment]
Ahhh jetzt sehe ich es auch. Danke Thomas.
