### ISSUE TITLE
Willkommenstexte nicht übersetzt

### ISSUE THREAD

**Issue by AllanScheSar** [KerbalSpaceProgramDe/KSP-Deutsch-Patch#24]
Warum werden die Texte, welche bei ersten betreten der Gebäude stehen nicht übersetzt. Hat es etwas damit zutun, dass der Farbecode nicht berücksichtigt wurde?

@ThomasKerman ich weiß nicht mehr weiter. Ich habe es nun 30 Minuten versucht, aber KSP lässt nicht mit sich verhandeln (zumindest mir gegenüber).

Dies sind die entsprechenden Stellen:
- [Tracking Station ](https://github.com/KerbalSpaceProgramDe/KSP-Deutsch-Patch/blob/master/GameData/KSP%20Deutsch%20Patch/TrackingStation.cfg#L93)
- [Editor](https://github.com/KerbalSpaceProgramDe/KSP-Deutsch-Patch/blob/master/GameData/KSP%20Deutsch%20Patch/Editor.cfg#L187)
- [Spacecenter](https://github.com/KerbalSpaceProgramDe/KSP-Deutsch-Patch/blob/master/GameData/KSP%20Deutsch%20Patch/Spacecenter.cfg#L55)

**Comment by AllanScheSar** [comment]
@ThomasKerman ich bekomme es nicht hin.
Ich habe nun alles möglich versucht. Ich habe mir logs erzeugt und die Texte daraus vollständig kopiert. Außerdem habe ich escaped, aber die Texte werden nicht angezeigt.

Probiert habe ich es mit der Mission Control. Wenn ich wüsste was da falsch ist, kann ich es auf die anderen übertragen.

Sag mir bitte was hier falsch läuft @ThomasKerman 

[Hier](https://github.com/KerbalSpaceProgramDe/KSP-Deutsch-Patch/blob/master/GameData/KSP%20Deutsch%20Patch/Spacecenter.cfg#L97) der direkte Link zur Stelle.

**Comment by StollD** [comment]
Die Zeile hat in KSP einen Zeilenumbruch (\ r) hinten dran. Füg den ein, und es klappt.

**Comment by AllanScheSar** [comment]
Okay, dass werde ich nachher gleich bei allen fraglichen Zeilen probieren. Aber wie finde ich das korrekt heraus? Probieren ist da nicht der richtige Weg - meiner Meinung nach.
Zumal #25 bestimmt in die gleiche Richtung geht.

**Comment by StollD** [comment]
Du musst die rohen Logs nehmen und in deinem Editor anschalten, dass er Zeilenumbrüche visualisiert (In Notepad++: Ansicht, Nicht druckbare Zeichen, Zeilenumbrüche).
CR ist dann `\r`, LF ist `\n` und CRLF ist `\r\n`

**Comment by AllanScheSar** [comment]
@ThomasKerman  ich habe nun 5 mal diesen Text ersetzt und jedes CR, LF, CRLF erzetzt (waren nur zwei). Der Text wird aber nicht angezeigt.

Ich bin mir meinen Nerven am Ende, aber ich will, dass diese Übersetzungen mit drin sind im KDP 3.0.
Kannst du dich bitte daran setzen?
Ohne die Texte möchte ich den KDP nicht veröffentlichen, aber ich komm einfach nicht weiter.

**Comment by StollD** [comment]
Ist erledigt
