### ISSUE TITLE
Übersetzung wird nicht verwendet.

### ISSUE THREAD

**Issue by AllanScheSar** [KerbalSpaceProgramDe/KSP-Deutsch-Patch#25]
Hallo @ThomasKerman 

es wird in die Übersetzung nicht angezeigt, wenn man ein Spielstand löschen will. 
Der Text befindet sich in [dieser](https://github.com/KerbalSpaceProgramDe/KSP-Deutsch-Patch/blob/master/GameData/KSP%20Deutsch%20Patch/MainMenu.cfg#L787) Zeile.

![fehler1](https://cloud.githubusercontent.com/assets/10440688/20029951/162eec9c-a35b-11e6-97b0-1611fefa1b73.JPG)

Warum wird er nicht übersetzt Thomas?

**Comment by StollD** [comment]
Weil ? und . nicht escaped sind (\ davorschreiben). In Regex sind das Modifikatoren, die nicht für ? und . stehen, sondern das Verhalten des Regexes beeinflussen

**Comment by AllanScheSar** [comment]
Ohhh das war mir entfallen. Dann muss ich noch mal über alle Texte drüber gehen. Aber das erklärt auch, warum die Texte (Willkommen und Gebäudebeschreibungen) nicht übersetzen werden.

In einem Satz zum Beispiel "Das ist aber cool! Ich werde es umsetzen Thomas." muss ich also in der Übersetzung schreiben:
"Das ist aber cool! Ich werde es umsetzen Thomas."

Oder muss das auch im englischen Text enthalten sein?

**Comment by StollD** [comment]
Nur im englischen Text, in der Übersetzung nichts escapen

**Comment by AllanScheSar** [comment]
Wir gemacht Sir (macht auch im zweiten Nachdenken mehr Sinn :roll_eyes: )

**Comment by AllanScheSar** [comment]
@ThomasKerman Ich habe die Zeile nun Escaped und es wird dennoch nicht angezeigt.
https://github.com/KerbalSpaceProgramDe/KSP-Deutsch-Patch/blob/master/GameData/KSP%20Deutsch%20Patch/MainMenu.cfg#L780

Was läuft da falsch?

**Comment by AllanScheSar** [comment]
Hallo @ThomasKerman ,
ich habe versucht diesen Text mit einem \r am Ende zu übersetzen (angezeigt zu bekommen), aber er will nicht.
Alle von dir genannten Punkte habe ich ausprobiert, bin aber nicht weiter gekommen :(

**Comment by AllanScheSar** [comment]
@ThomasKerman  ich habe nun 5 mal diesen Text ersetzt und jedes CR, LF, CRLF erzetzt (waren nur zwei). Der Text wird aber nicht angezeigt.

Ich bin mir meinen Nerven am Ende, aber ich will, dass diese Übersetzungen mit drin sind im KDP 3.0.
Kannst du dich bitte daran setzen?

**Comment by StollD** [comment]
Du musst die `\r\n` am Ende ignorieren. Die kommen vom Logger.

**Comment by AllanScheSar** [comment]
Ich bin doof und Thomas hast es hinbekommen. Der Text will mich einfach nur verarschen. Das gleiche stand gestern schon einmal auf dem Plan, aber okay. Das Ergebnis zählt!
