### ISSUE TITLE
Übersetzung Pilotenauswahl nicht komplett

### ISSUE THREAD

**Issue by AllanScheSar** [KerbalSpaceProgramDe/KSP-Deutsch-Patch#27]
Hallo @ThomasKerman ,

ich habe Texte bei der Pilotenauswahl eingefügt, damit das Gesamtergebnis besser aussieht.
Dieses mal habe ich 3 von 4 Regexs selbstständig hinbekommen nur Streckt die Übersetzung bei den Funds Zeichen. Wie muss ich das machen?

Außerdem würde ich gern wissen, warum Courage und Dummheit nicht angezeigt wird in Deutsch. Das sind doch nur einfache Texte. Ich habe selbst schon \r versucht, aber es klappte nicht.

Es handelt sich um die Datei Spacecenter etwa ab Zeile 1.100

![fehler_pilotenauswahl](https://cloud.githubusercontent.com/assets/10440688/20036731/af3ef944-a410-11e6-881e-c98f36e5d251.JPG)

**Comment by StollD** [comment]
Weil \d nur Zahlen erkennt. Da sind aber auch Kommas und Punkte drin.

Ersetzt das \d\* mit .\* und es klappt

**Comment by AllanScheSar** [comment]
.\* hat nicht geklappt. die Übersetzung für Next Hire hat nicht funktioniert.

**Comment by StollD** [comment]
Geht bei mir perfekt: `Next Hire: <sprite=2 tint=1> (.*)`

http://i.imgur.com/eJV6MWa.png

**Comment by AllanScheSar** [comment]
Ich habe Punkt und Komma noch getauscht.
Problem gelöst.
