### ISSUE TITLE
Anzeigen Hauptmenü in KSP 1.2.2 verschoben

### ISSUE THREAD

**Issue by AllanScheSar** [KerbalSpaceProgramDe/KSP-Deutsch-Patch#29]
Hallo @ThomasKerman ,

mit KSP 1.2.2 gibt es Übersetzungsprobleme mit dem KDP.
Wie du am Screenshot sehen kannst.
![screenshot0](https://cloud.githubusercontent.com/assets/10440688/21566570/6ee7e8d8-cea4-11e6-9832-a69220941c52.png)

Bekommst du diesen Bug behoben?

**Comment by StollD** [comment]
Ich kann den Bug per se beheben, wir haben aber ein anderes Problem. Die Schriftart wird nicht mehr ersetzt, was dazu führt dass Unicode mit unserer Font nichtmehr ordentlich dargestellt werden

Und ohne 90$ für irgendein komisches Unity Asset auszugeben wird das wohl nicht anders gehen - es sei den wir bauen das MainMenu um (Bei aller Liebe, aber ich weigere mich für dieses Projekt soviel Geld auszugeben - auch im Hinblick auf die Communityarbeit (wer ne tolle Übersetzung für seine Sprache machen will bezahlt Geld, nein danke. Dafür bin ich zu liberal :P))

**Comment by AllanScheSar** [comment]
Ohhh misst. Was bedeutet es, dass Main Menu umzubauen?
Ich selbst bin auch nicht bereits 90 $ auszugeben für die KDP. Da sage ich lieber der Community, dass sie leider auf die Lokalisierung von SQUAD warten müssen (geschätzt Okt. 2017).

**Comment by AllanScheSar** [comment]
Hallo Thomas ich habe von yrou eine Nachricht erhalten. Darin war diese Main Menu CFG Datei:
https://drive.google.com/file/d/0B7cLVW9ZGJYKOXV4X2p3dGU0Zjg/view

Das Ergebnis sieht dann wie folgt aus:
https://lh3.googleusercontent.com/F7amacSDQ1ypx9Gs6HGDn2vz02Ha82iH3bzqIO-edJUmzFse_JjSfBeIWOP7HJK4uO6oIYhEGH0AMbA=w1366-h667

Kannst du einmal Probieren, ob das uns hilft?

**Comment by AllanScheSar** [comment]
Problem in KSP 1.3 nicht mehr vorhanden.
