### ISSUE TITLE
Start Menüs keine Bezeichnungen

### ISSUE THREAD

**Issue by Ashgar0815** [KerbalSpaceProgramDe/KSP-Deutsch-Patch#3]
Gleich zu Beginn des Spiels fehlen bei den ganzen Menüs die Bezeichnungen, steht in jeder Zeile nur ein <|.

Gruß Jens

**Comment by StollD** [comment]
Kannst du bitte einen Screenshot vom Fehler hochladen?

**Comment by Ashgar0815** [comment]
![screenshot1](https://cloud.githubusercontent.com/assets/20297084/16599848/92385cb8-4304-11e6-86bf-4a017be1f30c.png)

**Comment by Ashgar0815** [comment]
sorry für die späte Antwort, hatte heute mittag keine Zeit mehr fürn screen ( wusste nicht wie das in KSP geht)

Gruß Jens
