### ISSUE TITLE
Loading... aus Loading.cfg wird nicht übersetzt

### ISSUE THREAD

**Issue by AllanScheSar** [KerbalSpaceProgramDe/KSP-Deutsch-Patch#31]
Loading... wird in der Loading.cfg nicht übersetzt

KSP Version 1.3.1
![loading](https://user-images.githubusercontent.com/10440688/31575058-fbf84864-b0dd-11e7-8ea6-1107ffab8831.JPG)
![loading1](https://user-images.githubusercontent.com/10440688/31575071-3ebf3428-b0de-11e7-94de-e52c7ac4c112.JPG)

**Comment by StollD** [comment]
Also, im Ladebildschirm wird es immernoch nicht übersetzt, allerdings in den Bildschirmen zwischen den Szenen funktioniert es jetzt

https://i.imgur.com/bZFl8Rn.png

**Comment by AllanScheSar** [comment]
Man versucht einen Bug zu schließen und macht keinen neuen auf. Das gibt es doch nicht :D

**Comment by AllanScheSar** [comment]
@StollD du hast gemeint, dass das nicht übersetzt wird, dafür aber die Tipps. Der Grund ist, dass wir Code deaktivieren mussten aufgrund von Blödsinn. Können wir nicht das Loading... ebenfalls in den aktiven Bereich packen?

**Comment by StollD** [comment]
Das hab ich schon gemacht, allerdings vermute ich, dass dieses Loading einfach so früh angezeigt wird, dass unser Plugin da nichts mehr machen kann.

**Comment by AllanScheSar** [comment]
Lassen wir diesen Bug offen?

**Comment by StollD** [comment]
Ich hab jetzt die Übersetzungen im Ladebildschirm einfach wieder aktiviert. Solange wir ordentlich mit den scene-Werten arbeiten und nicht zu viel Unsinn drin haben, funktioniert das eig. ganz gut.

Das Loading wird jetzt übersetzt
