### ISSUE TITLE
Übersetzung Settings an einer Stelle nicht ausgeführt

### ISSUE THREAD

**Issue by AllanScheSar** [KerbalSpaceProgramDe/KSP-Deutsch-Patch#32]
Ich verstehe nicht, warum diese Übersetzung nicht beachtet wird von unserem Patch.

![settings](https://user-images.githubusercontent.com/10440688/31575175-c49071b4-b0e0-11e7-8c54-93eba4bd3d4e.JPG)

Wenn dieser Bug behoben ist, dann sind die Settings auf 1.3.1 gepatched.

**Comment by StollD** [comment]
Weil die Klammern in Regex reservierte Zeichen darstellen. Die müssen mit einem Backslash davor escaped werden

Ungefähr so

```
TRANSLATION
{
    text = Throttle \(Incremental\)
    translation = Schub (Schrittweise)
}
```

**Comment by StollD** [comment]
Sollte jetzt funktionieren
