### ISSUE TITLE
Leerzeichen am Anfang eines Satzes

### ISSUE THREAD

**Issue by AllanScheSar** [KerbalSpaceProgramDe/KSP-Deutsch-Patch#33]
Hallo,

heute bei der Bugsuche ist mir in der Tracking Station aufgefallen, dass am Anfang des Satzes ein Leerzeichen eingefügt wird.
![leerzeichen tracking station](https://user-images.githubusercontent.com/10440688/31582862-3ae7b40e-b18f-11e7-9c8a-99513d9fbb03.JPG)

In der CFG ist aber kein Leerzeichen vorhanden.
https://github.com/KerbalSpaceProgramDe/KSP-Deutsch-Patch/blob/master/GameData/KSP%20Deutsch%20Patch/TrackingStation.cfg#L150

**Comment by StollD** [comment]
Das würde ich eher auf Squad schieben, und wie die die Texte formattieren

**Comment by AllanScheSar** [comment]
Ebenfalls Zähneknirschend geschlossen.
Ursache: SQUAD (muss ich mehr schreiben)?

Unser Code ist sauber.
