### ISSUE TITLE
Willkommenstext SPH/ VAB wird in nur in einem der beiden Gebäude gezeigt

### ISSUE THREAD

**Issue by AllanScheSar** [KerbalSpaceProgramDe/KSP-Deutsch-Patch#34]
Es gibt den technischen Bug, dass in einem neuen Savegame (Sandbox) der Willkommenstext VAB/ SPH nur in der Facility angezeigt wird, die man als erstes Besucht.
Wenn ich das SPH besuche, dann ist der Text korrekt auf Deutsch. Im Anschluss gehe ich in VAB und es taucht kein Text auf (weder Englisch noch Deutsch).

Wenn das selbe Beispiel im VAB gestartet wird, dann ist der erste Satz übersetzt, aber der Rest bleibt englisch. Gehe ich danach in das SPH, dann taucht kein Willkommenstext auf.

**Comment by AllanScheSar** [comment]
Thomas ich bekomme den Fehler nicht raus. Ich habe viel getestet und gemacht, aber nichts klappte bisher. Der Bug ist immer noch vorhanden.
Meine Idee ist, da es nun einzelne Satzschnippsel sind und KSP weiß, dass dieser Schnippsel schon einmal verwendet wurde, muss es den Text nicht noch mal anzeigen.

Soll ich versuchen alles in eine Übersetzung zu schreiben?

**Comment by StollD** [comment]
Der Gebäudetext wird selbst in der Stock Version nur einmal angezeigt, weil Squad nicht prüft ob man in VAB oder SPH ist, sondern ob man in einem Editor ist. 

Und bei mir wird der Text im VAB mit deinen Änderungen korrekt angezeigt.

**Comment by AllanScheSar** [comment]
Bug Zähneknirschend geschlossen, da wir dann am SQUAD System nichts ändern können.
Warum ist SQUAD dieser Bug nie aufgefallen?
