### ISSUE TITLE
Problem mit Text

### ISSUE THREAD

**Issue by deb10er0** [KerbalSpaceProgramDe/KSP-Deutsch-Patch#4]
Hi,
ich habe die beiden Ordner in den GameData Ordner (mit Modulmanager-Datei habe ich es auch probiert) kopiert. Wenn ich jetzt das Spiel starte steht überall im Menü nur "<|". Wenn ich die Ordner wieder lösche, passt wieder alles. Mache ich etwas falsch oder ist da noch ein Fehler in der Datei?

Vielen Dank schon mal.
Gruß
deb10er0

**Comment by AllanScheSar** [comment]
Problem ist bekannt und wurde von @ThomasKerman gestern behoben.
Die neue Version muss noch zur Verfügung gestellt werden.

**Comment by deb10er0** [comment]
Ah... ok. Danke für die Hilfe.

**Comment by StollD** [comment]
Ist jetzt released
