### ISSUE TITLE
Zurück/zurück Abbrechen/abbrechen

### ISSUE THREAD

**Issue by Idinyphe** [KerbalSpaceProgramDe/KSP-Deutsch-Patch#5]
Manche Wörter erfordern es im Kontext groß geschrieben zu werden, andere erfordern es im Kontext klein geschrieben zu werden.

Wie funktioniert der Übersetzungsmechanismus?

Falls es nicht anders möglich ist würde ich vorschlagen zumindest im "Menü" alles klein zu schreiben.

**Comment by StollD** [comment]
Sofern das nicht spezifiziert ist, achtet das Plugin auf Groß- und Kleinschreibung. Ich würde da auf einen Fehler in den .cfgs tippen. (Oder ich hab schon vergessen wie mein eigenes Plugin funktioniert :rolleyes:)

**Comment by AllanScheSar** [comment]
Es handelte sich um einen Fehler in der .CFG Datei. Fehler wurde bereits behoben.
