### ISSUE TITLE
Beschreibungstexte Texte unter "Szenarios" und "Tutorials" sind nicht übersetzt

### ISSUE THREAD

**Issue by Idinyphe** [KerbalSpaceProgramDe/KSP-Deutsch-Patch#6]
Neben dem Titel für die Tutorials sind die beschreibenden Texte neben den Szenarios nicht übersetzt. Diese tauchen auch in den ursprünglichen Files für die Übersetzung nicht auf und wurden deswegen nicht übersetzt.

Wie funktioniert es einen neuen Text zu übersetzen? Einfach nach bekanntem Muster in den cfg Files hinzufügen?

**Comment by StollD** [comment]
Ja, einfach das bestehende Muster nachbilden.

**Comment by AllanScheSar** [comment]
@Idinyphe Idinyphe würdest du diese Aufgabe übernehmen? Bei meiner Überprüfung ist mir das nämlich auch aufgefallen

**Comment by AllanScheSar** [comment]
Mir fällt gerade ein, dass diese Übersetzung unter SpaceCenter enthalten sein kann. Bitte noch nicht übersetzen.

**Comment by StollD** [comment]
Ist sie nicht. Wir haben nirgendwo die Szenen forciert also sind die Namen rein für die Seele

**Comment by AllanScheSar** [comment]
Thomas dann bitte die Szenarien als Log herausschreiben.

**Comment by Idinyphe** [comment]
Ich bin mir jetzt unsicher und möchte nicht wieder wem was "wegnehmen"... soll ich die Szenen und Tutorials jetzt machen oder nicht?

Wenn ja bitte um Bestätigung :)

**Comment by AllanScheSar** [comment]
Ja das kannst du machen danke. Aber vielleicht kann @ThomasKerman die Texte in eine Log Datei raus schreiben. Dann brauchst du die englischen Texte nicht abschreiben.

**Comment by Idinyphe** [comment]
Ok. Dann warte ich auf die Texte. Bitte hier Posten!

**Comment by AllanScheSar** [comment]
Thema wird geschlossen. Szenarien und Tutorials werden getrennt behandelt.
