### ISSUE TITLE
Übersetzung wird nicht angezeigt

### ISSUE THREAD

**Issue by AllanScheSar** [KerbalSpaceProgramDe/KSP-Deutsch-Patch#9]
- Bereits übersetzte Zeile (Secondary) wird im Spiel nicht angezeigt ([Quellzeile]
  ![screenshot9](https://cloud.githubusercontent.com/assets/10440688/16707839/f461d0c4-45dc-11e6-858d-fd84b9656d0b.png)

**Comment by StollD** [comment]
In dem Bild sehe ich nirgendwo was mit Secondary :stuck_out_tongue_closed_eyes: 

Gehören die Bilder evtl. in #8 ?

**Comment by AllanScheSar** [comment]
Passt doch :P

**Comment by AllanScheSar** [comment]
behoben
